### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by acalvino4** [jalendport/craft-readtime#24]
Will you be updating this plugin for craft 4?

**Comment by darylknight** [comment]
+1

**Comment by masonry47** [comment]
+1. Thanks!

**Comment by engram-design** [comment]
@jalendport Another one that's been suggested for our [Craft 3 migration project](https://verbb.io/craft-3), or just let me know if you're planning to upgrade.

**Comment by thijskaspers** [comment]
+1

**Comment by LouisCuvelier** [comment]
Would be very much appreciated 😍

**Comment by mark-chief** [comment]
+1 PLEEEEASE

**Comment by acalvino4** [comment]
Just want to point out that the license is MIT, so anyone who's got some time is free to fork, do the update, and report back. Also, maybe just thumbs up the first post to avoid spamming people with comments.

**Comment by engram-design** [comment]
@acalvino4 Good suggestion, and see the PR for this already https://github.com/jalendport/craft-readtime/pull/23.

From what @jalendport has mentioned to me, he's planning to upgrade this to Craft 4, so we'll leave this with him.

**Comment by jalendport** [comment]
Here's an update on where things are at: https://twitter.com/jalendport/status/1628813156888809475

**Comment by jalendport** [comment]
Just released [2.0.0-beta.1](https://github.com/jalendport/craft-readtime/releases/tag/2.0.0-beta.1), which is a fairly straightforward upgrade of the codebase to be Craft 4 ready. It's tagged as a beta at this point because I haven't had a chance to test it very thoroughly yet (particularly with a complex matrix or supertable field setup), and also because I'd like to get Neo support in, as well as a more thorough refactor of the codebase, before I tag a final version of 2.0.0.

Thanks for y'all's patience - let me know if you run into issues with the new version and I'll make sure they're fixed right quick 💪
